apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utravs
  source:
    repoURL: git@github.com:alisz1992/utravs-devops-task.git
    targetRevision: main
    path: gitops/components/tracing
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
