all:
  children:
    lb_api:
      hosts:
        lb-api-1:
          ansible_host: 95.182.116.206
        lb-api-2:
          ansible_host: 217.60.36.181

    lb_ingress:
      hosts:
        lb-ing-1:
          ansible_host: 95.182.87.236
        lb-ing-2:
          ansible_host: 217.60.5.153

    control_plane:
      hosts:
        cp1:
          ansible_host: 217.60.63.89
        cp2:
          ansible_host: 104.253.79.218
        cp3:
          ansible_host: 104.252.89.101

    workers:
      hosts:
        w1:
          ansible_host: 31.56.146.85
        w2:
          ansible_host: 95.182.88.89

  vars:
    ansible_user: root
    ansible_become: true
