replicaCount: 2

image:
  repository: ghcr.io/alisz1992/consumer
  tag: "1.0.3"
  pullPolicy: IfNotPresent

kafka:
  bootstrap: utravs-kafka-kafka-bootstrap.kafka:9092
  topic: orders
  consumerGroup: orders-consumers-prod
  autoOffsetReset: earliest

agentInject:
  enabled: true
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/role: "consumer-prod"
    vault.hashicorp.com/agent-inject-secret-kafka-creds: "kv/data/consumer"
    vault.hashicorp.com/agent-inject-template-kafka-creds: |
      {{- with secret "kv/data/consumer" -}}
      CONSUMER_TOKEN={{ .Data.data.token }}
      {{- end }}

ingress:
  enabled: true
  host: consumer.unit5chd.qzz.io
  path: /
  tls: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
